### ISSUE TITLE
Alternative/additional pkgs

### ISSUE THREAD

**Issue by jolheiser** [candrewlee14/webman#17]
I see webman supports local packages, which is nice, but it would also be nice to be able to support alternative/additional `pkgs` repos, in case some user wants to curate their own pkgs and/or groups.

I would be open to making a PR if you like the proposal.

**Comment by candrewlee14** [comment]
That's something I've been thinking about. It'll definitely be a useful feature as time goes on, but I also hope that the majority of package recipe maintainers will contribute those back to the standard repo, especially as this project grows.

I like this idea, but no rush to implement it, because I think centralizing those packages into the standard repo (at least for now) will be better.
